### ISSUE TITLE
Sway in meta-wayland?

### ISSUE THREAD

**Issue by dev-0x7C6** [MarkusVolk/meta-retro-wayland#2]
Hi,

Great work with sway, I've started wondering if more people can benefit from your work. Did you consider creating another layer for plain software (without configuration and less dependencies). My suggestion is to create meta-wayland or (meta-sway?) and register it in https://layers.openembedded.org/layerindex.

p.s.
Since this is not an issue, you might want to move this in discussion section on github project page.

Cheers,
Bartłomiej

**Comment by MarkusVolk** [comment]
I actually thought about outsourcing the wayland recipes, so I tried to keep the config out of the bb files.
This shouldn't be too much work. I think maybe meta-wayland would be more unspecific, so the other wlroots related recipes eg. wayfire could be put there  as well?

**Comment by dev-0x7C6** [comment]
> This shouldn't be too much work. I think maybe meta-wayland would be more unspecific, so the other wlroots related recipes eg. wayfire could be put there as well?

Yes, `meta-wayland` can acquire more wayland and semi wayland specific software :-)

**Comment by MarkusVolk** [comment]
It looks like everythings still working after splitting of the wayland recipes. Hopefully this could be closed
